name: 测试服编译

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '环境'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  test_publish:
    name: 发布测试版
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - uses: actions/checkout@v4
      - name: 使用 Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 版本计算
        id: version
        uses: codacy/git-version@2.8.0
        with:
          prefix: "test-"

      - name: 本次版本号
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: 上一次版本号
        run: |
          echo ${{ steps.version.outputs.previous-version }}

      - name: 安装依赖
        run: npm install
      - name: 编译
        run: npm run build:dev
      - name: 注入版本号
        run: echo ${{ steps.version.outputs.version }} >> ./dist/version.txt
      - name: 打包
        run: tar -czf inkmaster.tar.gz ./dist
      - name: 发布
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          target_commitish: ${{ github.event.inputs.target_commitish }}
          files: inkmaster.tar.gz
