name: 测试服编译

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '环境'
        required: true
        type: choice
        options:
          - 123
          - product312ion

jobs:
  test_publish:
    name: 发布测试版
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display GitVersion config
        uses: gittools/actions/gitversion/command@v3.0.0
      # - name: 版本计算
      #   id: version
      #   run: gitversion
      # - name: 本次版本号
      #   run: |
      #     echo ${{ steps.version.outputs.MajorMinorPatch }}
      #     echo ${{ steps.gitversion.outputs.MajorMinorPatch }}
      #     echo ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}
      #     echo ${{ steps.gitversion.outputs.FullSemVer }}
      # - name: 上一次版本号
      #   run: |
      #     echo ${{ steps.version.outputs.previous-version }}
      # - name: 注入版本号
      #   run: echo ${{ steps.version.outputs.version }} >> ./version.txt
      # - name: 打包
      #   run: tar -czf inkmaster.tar.gz ./version.txt
      # - name: 发布
      #   uses: softprops/action-gh-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.version.outputs.version }}
      #     target_commitish: ${{ github.event.inputs.target_commitish }}
      #     files: inkmaster.tar.gz
